alpaca:
  API_KEY: PKR3MGOKBHSR4RS8J17Q
  SECRET_KEY: kjuKItCpKgOy2HcrdEtUzJnaDgoHaQrXozLpI95P
  BASE_URL: https://paper-api.alpaca.markets

database:
  url: "mysql+pymysql://trading_user:your_password@localhost:3306/trading_bot"

trading:
  symbols:
    - "AAPL"
    - "MSFT"
    - "GOOGL"
  timeframe: "15Min"
  initial_balance: 200000
  risk_per_trade: 0.01
