alpaca:
  API_KEY: PKR3MGOKBHSR4RS8J17Q
  SECRET_KEY: kjuKItCpKgOy2HcrdEtUzJnaDgoHaQrXozLpI95P
  BASE_URL: https://paper-api.alpaca.markets/v2

database:
  url: "postgresql://trading_bot:password@localhost/your_database_name"

trading:
  symbols:
    - "AAPL"
    - "MSFT"
    - "GOOGL"
  timeframe: "15Min"
  initial_balance: 200000
  risk_per_trade: 0.01
