alpaca:
  API_KEY: PKPWDQHHK0NELHJOGHJ4
  SECRET_KEY: JNdLs5ldleeNJ6Vz41ZM8S9qlspeZLJJSbxlhL61

database:
  url: "mysql+pymysql://trading_user:your_password@localhost:3306/trading_bot"

trading:
  symbols: ["AAPL", "MSFT", "TSLA"]
  max_positions: 3
  risk_percent: 0.01
  rsi_period: 14
  rsi_threshold: 30
