alpaca:
  API_KEY: PKR3MGOKBHSR4RS8J17Q
  SECRET_KEY: kjuKItCpKgOy2HcrdEtUzJnaDgoHaQrXozLpI95P
  BASE_URL: https://paper-api.alpaca.markets

database:
  url: "mysql+pymysql://trading_user:your_password@localhost:3306/trading_bot"

trading:
  symbols: ["AAPL", "MSFT", "TSLA"]
  max_positions: 3
  risk_percent: 0.01
  rsi_period: 14
  rsi_threshold: 30
